// ─── Static Data & Configuration ────────────────────────────────────────────

export const INITIAL_USERS = [
  {
    id: 1,
    firstName: 'Ana',
    lastName: 'Reyes',
    email: 'ana.reyes@pagasa.gov.ph',
    contact: '+639171112233',
    agency: 'PAGASA Marine Division',
    position: 'Senior Forecaster',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2022-03-12',
    lastLogin: '2026-02-19 08:10',
    avatarUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: 2,
    firstName: 'Liam',
    lastName: 'Cruz',
    email: 'liam.cruz@pagasa.gov.ph',
    contact: '+639181234567',
    agency: 'PAGASA ICT',
    position: 'Platform Admin',
    role: 'Admin',
    status: 'Active',
    memberSince: '2021-07-05',
    lastLogin: '2026-02-19 09:35',
    avatarUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: 3,
    firstName: 'Maya',
    lastName: 'Santos',
    email: 'maya.santos@dost.gov.ph',
    contact: '+639209876543',
    agency: 'DOST Analytics Unit',
    position: 'Data Analyst',
    role: 'Data Analyst',
    status: 'Pending',
    memberSince: '2026-01-20',
    lastLogin: 'Never',
    avatarUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    id: 4,
    firstName: 'Noel',
    lastName: 'Aquino',
    email: 'noel.aquino@pagasa.gov.ph',
    contact: '+639151234567',
    agency: 'PAGASA Forecast Center',
    position: 'Forecaster',
    role: 'Forecaster',
    status: 'Suspended',
    memberSince: '2023-11-14',
    lastLogin: '2026-02-10 13:01',
    avatarUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
  },

  // Remaining users
  {
    id: 5,
    firstName: 'Carla',
    lastName: 'Mendoza',
    email: 'carla.mendoza@pagasa.gov.ph',
    contact: '+639171223344',
    agency: 'PAGASA Marine Division',
    position: 'Assistant Forecaster',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2024-04-02',
    lastLogin: '2026-02-18 07:55',
    avatarUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    id: 6,
    firstName: 'Rafael',
    lastName: 'Torres',
    email: 'rafael.torres@pagasa.gov.ph',
    contact: '+639189991234',
    agency: 'PAGASA ICT',
    position: 'Backend Developer',
    role: 'Admin',
    status: 'Active',
    memberSince: '2022-09-19',
    lastLogin: '2026-02-19 10:02',
    avatarUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
  },
  {
    id: 7,
    firstName: 'Jasmine',
    lastName: 'Lopez',
    email: 'jasmine.lopez@dost.gov.ph',
    contact: '+639175551234',
    agency: 'DOST Analytics Unit',
    position: 'Junior Analyst',
    role: 'Data Analyst',
    status: 'Active',
    memberSince: '2025-03-11',
    lastLogin: '2026-02-18 16:20',
    avatarUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    id: 8,
    firstName: 'Victor',
    lastName: 'Delos Santos',
    email: 'victor.santos@pagasa.gov.ph',
    contact: '+639163331212',
    agency: 'PAGASA Forecast Center',
    position: 'Senior Forecaster',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2020-01-25',
    lastLogin: '2026-02-19 05:48',
    avatarUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
  {
    id: 9,
    firstName: 'Paolo',
    lastName: 'Navarro',
    email: 'paolo.navarro@pagasa.gov.ph',
    contact: '+639158887654',
    agency: 'PAGASA Marine Division',
    position: 'Wave Specialist',
    role: 'Forecaster',
    status: 'Pending',
    memberSince: '2026-02-01',
    lastLogin: 'Never',
    avatarUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: 10,
    firstName: 'Dianne',
    lastName: 'Garcia',
    email: 'dianne.garcia@pagasa.gov.ph',
    contact: '+639176667890',
    agency: 'PAGASA ICT',
    position: 'UI Engineer',
    role: 'Admin',
    status: 'Active',
    memberSince: '2023-06-14',
    lastLogin: '2026-02-19 09:02',
    avatarUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
  {
    id: 11,
    firstName: 'Erik',
    lastName: 'Villanueva',
    email: 'erik.villanueva@dost.gov.ph',
    contact: '+639159991111',
    agency: 'DOST Analytics Unit',
    position: 'Data Engineer',
    role: 'Data Analyst',
    status: 'Active',
    memberSince: '2022-02-18',
    lastLogin: '2026-02-17 14:12',
    avatarUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: 12,
    firstName: 'Marion',
    lastName: 'Castillo',
    email: 'marion.castillo@pagasa.gov.ph',
    contact: '+639188884321',
    agency: 'PAGASA Forecast Center',
    position: 'Shift Forecaster',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2024-10-03',
    lastLogin: '2026-02-18 23:41',
    avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    id: 13,
    firstName: 'Jose',
    lastName: 'Ramos',
    email: 'jose.ramos@pagasa.gov.ph',
    contact: '+639155552222',
    agency: 'PAGASA Marine Division',
    position: 'Marine Observer',
    role: 'Forecaster',
    status: 'Suspended',
    memberSince: '2021-05-09',
    lastLogin: '2025-12-12 11:30',
    avatarUrl: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: 14,
    firstName: 'Nicole',
    lastName: 'Bautista',
    email: 'nicole.bautista@pagasa.gov.ph',
    contact: '+639177771010',
    agency: 'PAGASA ICT',
    position: 'QA Engineer',
    role: 'Admin',
    status: 'Active',
    memberSince: '2023-01-22',
    lastLogin: '2026-02-19 08:40',
    avatarUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    id: 15,
    firstName: 'Kevin',
    lastName: 'Hernandez',
    email: 'kevin.hernandez@dost.gov.ph',
    contact: '+639199990000',
    agency: 'DOST Analytics Unit',
    position: 'Research Assistant',
    role: 'Data Analyst',
    status: 'Pending',
    memberSince: '2026-01-29',
    lastLogin: 'Never',
    avatarUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
  },
  {
    id: 16,
    firstName: 'Angel',
    lastName: 'Soriano',
    email: 'angel.soriano@pagasa.gov.ph',
    contact: '+639144445555',
    agency: 'PAGASA Forecast Center',
    position: 'Trainee Forecaster',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2025-11-17',
    lastLogin: '2026-02-19 06:15',
    avatarUrl: 'https://randomuser.me/api/portraits/men/16.jpg',
  },
  {
    id: 17,
    firstName: 'Therese',
    lastName: 'Lim',
    email: 'therese.lim@pagasa.gov.ph',
    contact: '+639133337777',
    agency: 'PAGASA Marine Division',
    position: 'Wave Model Specialist',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2022-12-08',
    lastLogin: '2026-02-18 18:05',
    avatarUrl: 'https://randomuser.me/api/portraits/women/17.jpg',
  },
  {
    id: 18,
    firstName: 'Bryan',
    lastName: 'Ferrer',
    email: 'bryan.ferrer@pagasa.gov.ph',
    contact: '+639166669999',
    agency: 'PAGASA ICT',
    position: 'DevOps Engineer',
    role: 'Admin',
    status: 'Active',
    memberSince: '2021-09-27',
    lastLogin: '2026-02-19 10:15',
    avatarUrl: 'https://randomuser.me/api/portraits/men/18.jpg',
  },
  {
    id: 19,
    firstName: 'Shiela',
    lastName: 'Domingo',
    email: 'shiela.domingo@dost.gov.ph',
    contact: '+639122223333',
    agency: 'DOST Analytics Unit',
    position: 'Statistician',
    role: 'Data Analyst',
    status: 'Active',
    memberSince: '2023-08-13',
    lastLogin: '2026-02-18 12:02',
    avatarUrl: 'https://randomuser.me/api/portraits/women/19.jpg',
  },
  {
    id: 20,
    firstName: 'Mark',
    lastName: 'Alvarez',
    email: 'mark.alvarez@pagasa.gov.ph',
    contact: '+639188881111',
    agency: 'PAGASA Forecast Center',
    position: 'Forecaster',
    role: 'Forecaster',
    status: 'Active',
    memberSince: '2024-02-05',
    lastLogin: '2026-02-19 07:33',
    avatarUrl: 'https://randomuser.me/api/portraits/men/20.jpg',
  },
];

export const ROLE_OPTIONS = ['Admin', 'Forecaster', 'Data Analyst'];

export const STATUS_OPTIONS = ['All', 'Active', 'Pending', 'Suspended'];

export const ROLE_DEFINITIONS = [
  {
    role: 'Admin',
    description: 'Full access to dashboard management, user approvals, and system configuration.',
    members: 4,
    icon: '⬡',
    color: 'violet',
  },
  {
    role: 'Forecaster',
    description: 'Can prepare, review, and submit official forecast charts and bulletins.',
    members: 18,
    icon: '◈',
    color: 'cyan',
  },
  {
    role: 'Data Analyst',
    description: 'Can review data quality pipelines, run analytics, and export reports.',
    members: 10,
    icon: '◇',
    color: 'emerald',
  },
];

export const STATUS_CONFIG = {
  Active: {
    dot: 'bg-emerald-400',
    badge: 'text-emerald-300 bg-emerald-400/10 border border-emerald-400/30',
    badgeLight: 'text-emerald-700 bg-emerald-50 border border-emerald-200',
  },
  Pending: {
    dot: 'bg-amber-400',
    badge: 'text-amber-300 bg-amber-400/10 border border-amber-400/30',
    badgeLight: 'text-amber-700 bg-amber-50 border border-amber-200',
  },
  Suspended: {
    dot: 'bg-red-400',
    badge: 'text-red-300 bg-red-400/10 border border-red-400/30',
    badgeLight: 'text-red-700 bg-red-50 border border-red-200',
  },
};

export const ROLE_COLOR_CONFIG = {
  violet: {
    icon: 'text-violet-400',
    bg: 'bg-violet-400/10 border-violet-400/30',
    badge: 'text-violet-300 bg-violet-400/10 border border-violet-400/20',
    badgeLight: 'text-violet-700 bg-violet-50 border border-violet-200',
    glow: 'shadow-violet-500/10',
    lightIcon: 'text-violet-600',
    lightBg: 'bg-violet-50 border-violet-200',
  },
  cyan: {
    icon: 'text-cyan-400',
    bg: 'bg-cyan-400/10 border-cyan-400/30',
    badge: 'text-cyan-300 bg-cyan-400/10 border border-cyan-400/20',
    badgeLight: 'text-cyan-700 bg-cyan-50 border border-cyan-200',
    glow: 'shadow-cyan-500/10',
    lightIcon: 'text-cyan-600',
    lightBg: 'bg-cyan-50 border-cyan-200',
  },
  emerald: {
    icon: 'text-emerald-400',
    bg: 'bg-emerald-400/10 border-emerald-400/30',
    badge: 'text-emerald-300 bg-emerald-400/10 border border-emerald-400/20',
    badgeLight: 'text-emerald-700 bg-emerald-50 border border-emerald-200',
    glow: 'shadow-emerald-500/10',
    lightIcon: 'text-emerald-600',
    lightBg: 'bg-emerald-50 border-emerald-200',
  },
};