import {
  BarChart3,
  Box,
  CalendarDays,
  CloudSun,
  FolderKanban,
  LayoutDashboard,
  Map,
  RadioTower,
  Settings,
  Users,
  Waves,
} from 'lucide-react';

export const DASHBOARD_MODULES = [
  {
    id: 'overview',
    label: 'Dashboard Overview',
    icon: LayoutDashboard,
    feature: 'overview',
    action: 'view',
    roles: ['admin'],
    adminTab: 'dashboard',
  },
  {
    id: 'projects-review',
    label: 'Projects Review',
    icon: Waves,
    feature: 'projects',
    action: 'review',
    roles: ['admin'],
    adminTab: 'charts',
  },
  {
    id: 'users',
    label: 'Users',
    icon: Users,
    feature: 'users',
    action: 'view',
    roles: ['admin'],
    adminTab: 'users',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: BarChart3,
    feature: 'analytics',
    action: 'view',
    roles: ['admin', 'forecaster'],
    adminTab: 'analytics',
    path: '/studio?section=analytics',
    disabledFor: ['forecaster'],
  },
  {
    id: 'calendar',
    label: 'Calendar',
    icon: CalendarDays,
    feature: 'calendar',
    action: 'view',
    roles: ['admin'],
    adminTab: 'calendar',
  },
  {
    id: 'models',
    label: 'Models',
    icon: Box,
    feature: 'models',
    action: 'view',
    roles: ['admin', 'forecaster'],
    adminTab: 'models',
    path: '/studio?section=models',
    disabledFor: ['admin', 'forecaster'],
  },
  {
    id: 'project-library',
    label: 'Project Library',
    icon: FolderKanban,
    feature: 'projects',
    action: 'viewOwn',
    roles: ['forecaster'],
    path: '/studio',
  },
  {
    id: 'observations',
    label: 'Observations',
    icon: CloudSun,
    feature: 'observations',
    action: 'view',
    roles: ['forecaster'],
    path: '/studio?section=observations',
    disabledFor: ['forecaster'],
  },
  {
    id: 'nowcast',
    label: 'Nowcast',
    icon: RadioTower,
    feature: 'nowcast',
    action: 'view',
    roles: ['forecaster'],
    path: '/studio?section=nowcast',
    disabledFor: ['forecaster'],
  },
  {
    id: 'map-viewer',
    label: 'Map Viewer',
    icon: Map,
    feature: 'map',
    action: 'view',
    roles: ['forecaster'],
    path: '/studio?section=map-viewer',
    disabledFor: ['forecaster'],
  },
  {
    id: 'report-builder',
    label: 'Report Builder',
    icon: Waves,
    feature: 'reports',
    action: 'create',
    roles: ['forecaster'],
    path: '/pdf',
    disabledFor: ['forecaster'],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    feature: 'settings',
    action: 'view',
    roles: ['admin', 'forecaster'],
    adminTab: 'settings',
    path: '/profile',
  },
];
